apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - servicemonitor.yaml
images:
  - name: 161230539245.dkr.ecr.us-east-1.amazonaws.com/eks-oidc-observability-dev-app
    newTag: main-4178b6ffb3e9190f22c7efe069950892931ffd7a # {"$imagepolicy": "flux-system:fastapi-app:tag"}
