apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::161230539245:role/eks-oidc-observability-dev-fluent-bit-irsa
